name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      #      - uses: actions/setup-node@v2
      #        with:
      #          node-version: '15.x'
      #          registry-url: 'https://npm.pkg.github.com'
      #          scope: '@wutsi'
      #      - run: npm install uglify-js
      #      - run: npm publish
      #        env:
      #          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'
      #          scope: '@wutsi'
      - run: npm install uglify-js
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
